-- Role enum: pt-BR -> English
ALTER TYPE "role" RENAME VALUE 'LIDERANCA' TO 'ADMIN';
ALTER TYPE "role" RENAME VALUE 'COORDENACAO' TO 'COORDINATOR';
ALTER TYPE "role" RENAME VALUE 'PROFESSOR' TO 'TEACHER';
ALTER TYPE "role" RENAME VALUE 'AUXILIAR' TO 'ASSISTANT';
ALTER TYPE "role" RENAME VALUE 'RECEPCAO' TO 'RECEPTIONIST';

-- FunctionType: Teatro -> Eventos
ALTER TYPE "function_type" RENAME VALUE 'TEATRO' TO 'EVENTS';

-- LessonType: Culto Infantil -> Revisão, add Quiz/Gincana
ALTER TYPE "lesson_type" RENAME VALUE 'CULTO_INFANTIL' TO 'REVIEW';
ALTER TYPE "lesson_type" ADD VALUE 'QUIZ_GINCANA' AFTER 'REVIEW';
